
2017-09-11 15:19:32,715 - my_module - ERROR - error
2017-09-11 15:58:03,872 - TestProjectXXX - ERROR - test
2017-09-11 15:58:27,668 - TestProjectXXX - ERROR - test
2017-09-11 16:00:22,748 - TestProjectXXX111 - ERROR - testown
2017-09-11 16:00:22,751 - TestProjectXXX111 - ERROR - test123
2017-09-11 16:01:38,686 - TestProjectXXX - ERROR - test
2017-09-11 16:02:08,027 - TestProjectXXX - ERROR - test
2017-09-11 16:03:26,533 - TestProjectXXX - ERROR - test
2017-09-11 16:04:06,216 - TestProjectXXX - ERROR - test
2017-09-11 16:04:25,318 - TestProjectXXX - ERROR - test
2017-09-11 16:04:57,027 - TestProjectXXX - ERROR - test
2017-09-11 16:05:05,415 - TestProjectXXX - ERROR - test
2017-09-11 16:06:17,062 - TestProjectXXX - ERROR - test
2017-09-11 16:09:44,150 - TestProjectXXX - ERROR - test
2017-09-11 16:09:49,804 - TestProjectXXX - ERROR - test
2017-09-11 16:11:28,805 - TestProjectXXX - ERROR - test
2017-09-11 16:13:36,074 - TestProjectXXX - ERROR - test
2017-09-11 16:14:05,682 - TestProjectXXX - ERROR - test
2017-09-14 11:49:20,062 - TestProject - ERROR - Exception:[Errno 2] No such file or directory: 'datas/test_positive.json'
2017-09-14 14:21:29,523 - TestProject - ERROR - Exception:[Errno 2] No such file or directory: 'datas/test_positive.json'
2017-09-18 18:06:38,254 - TestProject - ERROR - Exception:<module 'json' from '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py'>
2017-09-18 18:06:38,260 - TestProject - ERROR - Exception:<module 'json' from '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py'>
2017-09-18 18:08:45,737 - TestProject - ERROR - Exception:post() got multiple values for keyword argument 'data'
2017-09-18 18:10:35,360 - TestProject - ERROR - Exception:unhashable type: 'dict'
2017-09-18 18:10:35,361 - TestProject - ERROR - Exception:unhashable type: 'dict'
2017-09-18 18:12:15,901 - TestProject - ERROR - Exception:'HttpRequest' object has no attribute 'data'
2017-09-18 18:12:15,903 - TestProject - ERROR - Exception:'HttpRequest' object has no attribute 'data'
2017-12-05 16:29:23,340 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-05 16:31:30,630 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 09:55:12,212 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 09:55:33,236 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 09:55:44,525 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 09:55:57,846 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 09:57:08,941 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 09:57:08,942 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 10:03:53,059 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 10:03:53,061 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 10:03:53,062 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 10:03:53,063 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 10:05:31,356 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 10:05:31,356 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 10:05:31,357 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 10:05:31,357 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.221:7771mobile
2017-12-06 10:58:59,105 - TestProject - ERROR - Exception:HTTPSConnectionPool(host='observatory.ofo.somobile', port=443): Max retries exceeded with url: /api/update (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x103276160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2017-12-06 10:58:59,110 - TestProject - ERROR - Exception:HTTPSConnectionPool(host='observatory.ofo.somobile', port=443): Max retries exceeded with url: /api/update (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1032760f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2017-12-06 10:58:59,113 - TestProject - ERROR - Exception:HTTPSConnectionPool(host='observatory.ofo.somobile', port=443): Max retries exceeded with url: /api/update (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x103276160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2017-12-06 10:58:59,115 - TestProject - ERROR - Exception:HTTPSConnectionPool(host='observatory.ofo.somobile', port=443): Max retries exceeded with url: /api/update (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1032760f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2017-12-06 10:59:13,767 - TestProject - ERROR - Exception:HTTPSConnectionPool(host='observatory.ofo.somobile', port=443): Max retries exceeded with url: /api/update (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10327d470>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2017-12-06 10:59:13,769 - TestProject - ERROR - Exception:HTTPSConnectionPool(host='observatory.ofo.somobile', port=443): Max retries exceeded with url: /api/update (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x103280470>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2017-12-06 10:59:13,771 - TestProject - ERROR - Exception:HTTPSConnectionPool(host='observatory.ofo.somobile', port=443): Max retries exceeded with url: /api/update (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1032802b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2017-12-06 10:59:13,774 - TestProject - ERROR - Exception:HTTPSConnectionPool(host='observatory.ofo.somobile', port=443): Max retries exceeded with url: /api/update (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1032800f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2017-12-11 10:18:41,798 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035000b8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,812 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103500940>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,822 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035220b8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,833 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103522828>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,848 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103522f60>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,859 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10352c6d8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,872 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035225c0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,881 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1006fb908>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,891 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103500a90>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,916 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10352c5f8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,927 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10352ce10>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,937 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10352c8d0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,949 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1033c5780>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 10:18:41,962 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103500f60>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,686 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034d4518>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,698 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034d4a58>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,706 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034f61d0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,715 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034f6940>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,724 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034ff0b8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,733 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034ff7f0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,742 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034f6828>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,750 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034d4dd8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,758 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034d4a20>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,767 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034ff0f0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,775 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034fff28>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,784 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034ff9e8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,792 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034c4c18>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:26:02,803 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034d4828>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,567 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035001d0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,575 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103500a58>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,583 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035221d0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,592 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103522940>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,602 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10352b0b8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,610 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10352b7f0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,618 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103522898>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,627 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103500dd8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,637 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103500828>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,647 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10352b0f0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,655 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10352bf28>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,665 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10352b9e8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,676 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1033c5c18>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:28:32,686 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103500780>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:31:31,979 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034f0160>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:31:32,007 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034dab70>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:31:32,031 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10350f198>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 14:31:32,042 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10350f908>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:23,978 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034e66a0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:23,989 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034d0ef0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:23,997 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035076a0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:24,006 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103507e10>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:24,016 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103510588>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:24,025 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103510cc0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:24,032 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103507940>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:24,041 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035070f0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:24,049 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034e6278>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:24,058 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103510128>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:24,075 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10355d438>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:24,090 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103510e80>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:24,103 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034e6128>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:24,112 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103507278>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:22:24,119 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103507860>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,239 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034da4a8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,250 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034dacf8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,258 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034fc4a8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,267 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034fcc18>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,275 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103506390>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,287 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103506ac8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,295 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034fca58>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,304 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034fc048>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,312 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034c9b38>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,321 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035061d0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,332 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10350d240>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,341 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103506d30>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,349 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034c9fd0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,359 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034daf28>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:23:48,371 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /janus/group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034fc630>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,500 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034ee710>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,509 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034eea90>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,517 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10350e3c8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,524 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10350eb38>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,535 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035182b0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,547 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035189e8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,559 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10350e828>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,567 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10350e048>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,574 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034dac50>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,580 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103518160>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,588 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103560160>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,596 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103518da0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,603 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034daf28>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,610 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034eeef0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:28:41,617 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10350e2e8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,049 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034e93c8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,058 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034e9b38>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,072 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035093c8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,079 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103509b38>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,086 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035132b0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,095 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035139e8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,104 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103509828>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,112 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103509048>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,122 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034d5c88>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,129 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103513080>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,141 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10355b160>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,150 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103513da0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,157 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034d5a90>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,164 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034e9eb8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:30:43,172 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103509588>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,095 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103514400>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,105 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103514b70>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,117 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103534400>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,127 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103534b70>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,135 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10353e2e8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,144 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10353ea20>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,152 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103534630>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,161 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103534080>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,167 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103500cc0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,176 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10353e198>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,183 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103586198>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,192 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10353edd8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,201 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103500dd8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,209 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103514ac8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:33:05,218 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103534550>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:45:24,086 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10339b6a0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 16:47:22,039 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1035190b8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-11 17:10:45,023 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.19.221', port=8081): Max retries exceeded with url: /bike/order/lowPowerNum (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034c3898>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 11:55:59,838 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?end_time=2017-12-09&level=city&zone_id=29006&start_time=2017-12-08 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10345c278>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 11:57:33,054 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?end_time=2017-12-09&zone_id=29006&level=city&start_time=2017-12-08 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10332b2b0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 11:57:33,065 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?end_time=2017-12-09&zone_id=29006&level=society&start_time=2017-12-08 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10332b9e8>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 11:57:45,915 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?start_time=2017-12-08&end_time=2017-12-09&level=city&zone_id=29006 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103331278>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 11:57:56,864 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?start_time=2017-12-08&level=city&zone_id=29006&end_time=2017-12-09 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103338160>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 11:58:16,756 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?end_time=2017-12-09&level=city&zone_id=29006&start_time=2017-12-08 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103437160>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 11:59:11,484 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?end_time=2017-12-09&level=city&zone_id=29006&start_time=2017-12-08 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103477160>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 11:59:37,102 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?start_time=2017-12-08&zone_id=29006&level=city&end_time=2017-12-09 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1033380f0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 12:00:35,269 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?end_time=2017-12-09&zone_id=29006&level=city&start_time=2017-12-08 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10332e0f0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 12:01:07,979 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?start_time=2017-12-08&zone_id=29006&level=city&end_time=2017-12-09 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034630f0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 12:01:33,724 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?zone_id=29006&end_time=2017-12-09&start_time=2017-12-08&level=city (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1033380f0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 12:03:40,984 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?start_time=2017-12-08&level=city&end_time=2017-12-09&zone_id=29006 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1033380f0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 12:09:44,863 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?end_time=2017-12-09&level=city&start_time=2017-12-08&zone_id=29006 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103430278>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 12:09:44,872 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?end_time=2017-12-09&level=society&start_time=2017-12-08&zone_id=29006 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034309b0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 12:10:52,007 - TestProject - ERROR - Exception:HTTPConnectionPool(host='10.6.26.159', port=8086): Max retries exceeded with url: /bike/order/lowPowerNum?start_time=2017-12-08&zone_id=29006&level=city&end_time=2017-12-09 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10345b240>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-12 15:12:22,720 - TestProject - ERROR - Exception:unhashable type: 'dict'
2017-12-12 15:13:12,963 - TestProject - ERROR - Exception:unhashable type: 'dict'
2017-12-12 15:14:04,719 - TestProject - ERROR - Exception:unhashable type: 'dict'
2017-12-12 15:16:53,462 - TestProject - ERROR - Exception:unhashable type: 'dict'
2017-12-12 15:17:41,972 - TestProject - ERROR - Exception:unhashable type: 'dict'
2017-12-12 15:18:36,896 - TestProject - ERROR - Exception:unhashable type: 'dict'
2018-01-24 16:22:18,384 - TestProject - ERROR - Exception:request() got an unexpected keyword argument 'param'
2018-01-24 16:22:54,939 - TestProject - ERROR - Exception:request() got an unexpected keyword argument 'param'
2018-01-24 16:31:13,035 - TestProject - ERROR - Exception:HTTPConnectionPool(host='192.168.2.133', port=8086): Max retries exceeded with url: /bike/schedule/get_poi?city_code=11001&type=am&date=20180122&area_code=1100101709290231 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103380320>: Failed to establish a new connection: [Errno 61] Connection refused',))
2018-02-02 14:34:19,556 - TestProject - ERROR - Exception:'get'
2018-02-02 14:37:26,064 - TestProject - ERROR - Exception:'get'
2018-02-02 14:37:37,550 - TestProject - ERROR - Exception:'get'
2018-02-02 14:37:46,610 - TestProject - ERROR - Exception:'get'
2018-02-02 14:39:42,096 - TestProject - ERROR - Exception:'get'
2018-02-02 14:39:57,691 - TestProject - ERROR - Exception:'get'
2018-02-08 11:16:51,739 - TestProject - ERROR - Exception:'get'
2018-02-08 11:18:51,118 - TestProject - ERROR - Exception:'get'
2018-02-08 11:20:58,915 - TestProject - ERROR - Exception:'get'
2018-02-08 11:21:10,038 - TestProject - ERROR - Exception:'get'
2018-02-08 11:23:08,618 - TestProject - ERROR - Exception:'get'
2018-02-08 11:30:31,633 - TestProject - ERROR - Exception:'get'
2018-02-08 11:37:47,182 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.219:5000http:
2018-02-08 11:38:25,620 - TestProject - ERROR - Exception:Failed to parse: 192.168.19.219:5000http:
2018-04-19 14:26:57,476 - my_module - ERROR - error
2018-04-19 16:25:17,108 - my_module - ERROR - error
